### ISSUE TITLE
Slurm Adapter partially incompatible with Slurm 18

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood_core#99] opened 2018-10-17 21:36 UTC
We should test with Slurm 18 and see what potential issues exists. We heard reports that the Active Jobs app did not work with Slurm 18 but job submission did work.

**Comment by MorganRodgers** [comment] 2018-11-16 19:57
Using [a modified ood-images-full](https://github.com/OSC/ood-images-full/tree/slurm18) I can confirm that job submission works. ActiveJobs fails if there are any active jobs...with the error:

```
Example Cluster: undefined method `split' for nil:NilClass
```

I'm looking into what is going on.

**Comment by MorganRodgers** [comment] 2018-11-16 21:43
It appears that the `squeue` format code `%b` has been removed which shifts the delimited text which causes things to be parsed incorrectly.

**Comment by MorganRodgers** [comment] 2018-11-16 22:10
Fix in c18fe4511bf3

**Comment by MorganRodgers** [comment] 2018-11-29 21:22
Closing because #110 is a much simpler fix.

**Closed** 2018-11-30 15:27 UTC
Labels: bug
