### ISSUE TITLE
Improve SGE `#info*` methods by including native attributes

### ISSUE THREAD

**Issue by MorganRodgers** [OSC/ood_core#114] opened 2018-12-13 16:01 UTC
As written SGE's `#info` and `#info_all` methods return a `JobInfo` with no native attributes. Native attributes do get used for example in ActiveJobs. After the initial release of SGE, revisit those methods and improve on native attribute reporting.

**Comment by matthu017** [comment] 2020-07-13 15:10
Duplicate of https://github.com/OSC/ood_core/issues/197

**Closed by matthu017** 2020-07-13 15:10 UTC
Labels: enhancement, sge
