### ISSUE TITLE
Getting list of batch server queues/partitions 

### ISSUE THREAD

**Issue by brianmcmichael** [OSC/ood_core#77] opened 2018-01-30 22:02 UTC
Community request:

Support getting a list of batch server queues/partitions

**Comment by nickjer** [comment] 2018-02-05 16:25
This is the same as https://github.com/OSC/ood_core/issues/1

**Comment by johrstrom** [comment] 2020-03-09 14:36
This is a duplicate of #1 so I'm closing.  This says community request, but there's no link to get further context. In any case, it looks like it's being discussed in the other ticket anyhow.

**Closed by johrstrom** 2020-03-09 14:36 UTC
